platform:ios, ‘7.0’
pod 'AFNetworking', '~> 2.3.1'
pod 'SDWebImage', '~>3.7'
pod 'ZXingObjC', '~> 3.0'
pod 'TPKeyboardAvoiding', '~> 1.2.6'
pod 'UMengAnalytics'
pod 'MBProgressHUD', '~> 0.9.1’
pod 'YYCache'
